### ISSUE TITLE
"amazon2csv" command not accessible in Windows 10

### ISSUE THREAD

**Issue by Suleman-Elahi** [tducret/amazon-scraper-python#1]
![image](https://user-images.githubusercontent.com/24384996/41212613-10ceba8e-6cf4-11e8-90db-fb9a891799c1.png)

**Comment by tducret** [comment]
Hello @Suleman-Elahi. Sorry to hear that :(
I don't have a Windows machine to test it.
Can you please check that `amazon2csv` is in your `<python_directory>/Scripts`?
Check also that this folder is in your **PATH**.

Source : https://superuser.com/questions/1204232/why-arent-pip-installed-executables-available-from-the-command-line?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by ReedJessen** [comment]
Just wanted to bump this issue as I have the same problem on Windows 10.

**Comment by Suleman-Elahi** [comment]
Yeah. The scripts folder is in the path but the actual problem is that it creates the binary file for Linux I think. Ideally, on Windows, it should create "amazon2csv.exe" file in the "Scripts" folder.
![image](https://user-images.githubusercontent.com/24384996/41269236-fb14cd80-6db8-11e8-99dd-d657f0fe6dd2.png)

**Comment by tducret** [comment]
I'm not sure that it is a binary file, could you please check with an editor?
What is written at the top 3-4 lines?
Could you add a .py extension to the file, and check again the execution in your command prompt?
Thank you, your help is greatly appreciated @Suleman-Elahi

**Comment by Suleman-Elahi** [comment]
The contents of the "amazon2csv" file are:
![image](https://user-images.githubusercontent.com/24384996/41274540-a282a07e-6dd2-11e8-9607-cab5268b5ced.png)
 And after running it with ".py" extension , following happens.
![image](https://user-images.githubusercontent.com/24384996/41274583-be912e8e-6dd2-11e8-93c2-e3aee50838cf.png)

**Comment by tducret** [comment]
That's weird. I am currently building a Windows VM to reproduce this issue and try to fix it. I'll let you know @Suleman-Elahi and @ReedJessen

**Comment by tducret** [comment]
Hello,
I renamed `amazon2csv` to `amazon2csv.py`, and updated the pip package accordingly.
Could you upgrade and test on Windows?
```bash
pip3 install --no-cache-dir -U amazonscraper
amazon2csv.py --keywords="Python programming" --maxproductnb=2
```

**Comment by tducret** [comment]
I tested on Windows today, and that worked properly.

Recap :
- make sure `<python_directory>/Scripts` is in your PATH
- execute `amazon2csv.py --help` in a `cmd` window to check

**Comment by davidliu1978** [comment]
![image](https://user-images.githubusercontent.com/14987441/46255037-2fe71780-c44d-11e8-8f6f-619675526d79.png)

Hi Tilbault. My issue may related to this one. It seems executing, but no output? can you help?

**Comment by tducret** [comment]
Hello @davidliu1978 
That is still difficult for me to reproduce it since I don't have a Windows host.
Could you try to execute this?
```
python3 amazon2csv.py --help
```

**Comment by davidliu1978** [comment]
thanks


![image](https://user-images.githubusercontent.com/14987441/46452511-01b94e80-c751-11e8-8f66-7c004367f10e.png)

**Comment by tducret** [comment]
@davidliu1978 Have you tried to install amazon2csv with `pip3 install -U amazonscraper`?
