### ISSUE TITLE
Currently, there are no sellers that can deliver this item to your location.

### ISSUE THREAD

**Issue by deadlyAce** [tducret/amazon-scraper-python#14]
When doing crawling, you will encounter the need to select the area before you can display the content. Can you tell me how to deal with this?

**Comment by deadlyAce** [comment]
like this place
![image](https://user-images.githubusercontent.com/28973083/50465599-241adb00-09d3-11e9-9638-ed878bd24cfc.png)
I need to change the area first
![image](https://user-images.githubusercontent.com/28973083/50465539-e9b13e00-09d2-11e9-87b0-e9ff1b83b252.png)
and then I can see the real content
![image](https://user-images.githubusercontent.com/28973083/50465655-8247be00-09d3-11e9-813e-d7c38b4ed2ac.png)

**Comment by deadlyAce** [comment]
like this place
![image](https://user-images.githubusercontent.com/28973083/50465670-a4414080-09d3-11e9-9dbb-6a5e5e62b5d6.png)

I need to change the area first
![image](https://user-images.githubusercontent.com/28973083/50465685-bde28800-09d3-11e9-9844-6c421fb058de.png)

and then I can see the real content
![image](https://user-images.githubusercontent.com/28973083/50465694-caff7700-09d3-11e9-93cd-26c77e5f0e60.png)

**Comment by tducret** [comment]
Hi @deadlyAce 
I'm sorry but I don't have much time to investigate your problem.
I hope you don't mind if I close the issue, since it is not directly related to this project.
