### ISSUE TITLE
Is it possible to obtain results for more than 15 products?

### ISSUE THREAD

**Issue by uzziwizzle** [tducret/amazon-scraper-python#21]
I am only able to get results of 15 products when I perform a search, even though I have set max_product_nb to a value greater than 15. Performing a manual search using the same keyword returns over 100 products on the amazon.com website. I'll appreciate any comments. Thank you.

**Comment by tducret** [comment]
Same problem here :(
It seems that Amazon may have changed the layout of the page.
We'll keep you updated.

**Comment by uzziwizzle** [comment]
Thx

**Comment by reuvencloud** [comment]
I've noticed using a basic python scrapy code that SPONSORED products that are dynamically pulled via java script are not being extracted... If you found a solution that would be great

**Comment by bobmarley29** [comment]
> I've noticed using a basic python scrapy code that SPONSORED products that are dynamically pulled via java script are not being extracted... If you found a solution that would be great

That one works https://github.com/drawrowfly/amazon-scraper
